[project]
name = "laser-prynter"
version = "0.2.5"
authors = [
  { name="tmck-code", email="tmck01@gmail.com" },
]
description = "terminal/cli/python helpers for colour and pretty-printing"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/tmck-code/laser-prynter"
Issues = "https://github.com/tmck-code/laser-prynter/issues"
